<?php

class GMaps {
	
	private $url = "http://maps.google.com/maps/api/staticmap?";
	private $center;
	private $zoom;
	private $size;
	private $maptype;
	private $markers = array();
	private $sensor = "false";
	private $optionals;
	
	public function GMaps() {
		
	}
	
	/**
	 * Sets the where the map should be center. 
	 * @param string $location: defines the center of the map, equidistant from all edges of the map. This parameter takes a location as either a comma-separated {latitude,longitude} 
	 * pair (e.g. "40.714728,-73.998672") or a string address (e.g. "city hall, new york, ny") identifying a unique location on the face of the earth.
	 */
	public function setCenter($location) {
		$this->center = $location;
	}
	
	/**
	 * Sets the zoom of the map. It's required by the API if no markers are setted.
	 * @param int $zoom: efines the zoom level of the map, which determines the magnification level of the map. This parameter takes a numerical value 
	 * corresponding to the zoom level of the region desired
	 */
	public function setZoom($zoom){
		$this->zoom = $zoom;
	}
	
	/**
	 * Sets the map's size. It's the size of the image generated by the API.
	 * @param string $size: defines the rectangular dimensions of the map image. This parameter takes a string of the form valuexvalue where horizontal pixels 
	 * are denoted first while vertical pixels are denoted second.
	 */
	public function setSize($size) {
		$this->size = $size;
	}
	
	/**
	 * defines the type of map to construct. There are several possible maptype values, including roadmap, satellite, hybrid, and terrain. 
	 * @param string $mapType: the type of may you want to API to generate. 
	 */
	public function setMapType($mapType) {
		$this->maptype = $mapType;
	}
	
	/**
	 * Sets the locations you want to be displayed in the map. 
	 * @param array $markers
	 */
	public function setMarkers(Array $markers){
		$this->markers = $markers;
	}
	
	/**
	 * Sets all the optional parameters available for the API. They include some of these:
	 *  - Language
	 *  - Format
	 *  - Path
	 *  - Visible
	 *  - Style
	 *  For further information about their possible values, plear referr to the Google Map's Static API at: http://code.google.com/apis/maps/documentation/staticmaps/
	 * @param $options: an asociative array of the option an it's value.
	 * i.e.: array("language" => "ES", "style" => "roadmap").
	 */
	public function setOptionals(Array $options) {
		$this->optionals = $options;
	}
	
	public function generateUrl() {
		
		// it should check that either zoom or markers are set. Otherwise, the URL will be wrong
		$url = "";
		// the zoom is only necesary when there are no markers available
		// otherwhise it's optional
		$url .= "size=" . $this->size;
		if($this->center) $url .= "center=" . $this->center;
		if(isset($this->zoom)) $url .= "&zoom=" . $this->zoom;
		if(isset($this->maptype)) $url .= "&maptype=" . $this->maptype;
		// now we set each of the markers available
		if( isset($this->markers)) {
			// there are markers available
			$markers = "color:red|label:A|";
			$i = 0;
			foreach($this->markers as $location){
				if( $i != 0 ) $markers .= "|"; 
				$markers .= "$location";
			}
			$url .= "&markers=" . urlencode($markers);
		}
		
		// set the optionals
		if( isset($this->optionals)) {
			foreach($this->optionals as $key=>$value){
				$url .= "&$key=$value";
			}
		}
		
		$url .= "&sensor=" . $this->sensor;
		
		return $this->url . $url;
		
		
	}
}

?>